name: Pipeline CI/CD


on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

# definicion de jobs del pipeline
jobs:
  # job de construcción de imagen Docker
  construccion:
    runs-on: ubuntu-latest 

    steps:
    - name: obtener repositorio
    # clonar repositorio
      uses: actions/checkout@v2 

    - name: configurar docker buildx
      uses: docker/setup-buildx-action@v1 

    - name: iniciar sesión dockerHub
      uses: docker/login-action@v1
      # usuario y contraseña almacenados en secrets
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: construir y subir imagen Docker
      uses: docker/build-push-action@v2 
      with:
        push: true 
        tags: your-dockerhub-username/nginx:latest

  # job de despliegue de la aplicación
  despliegue:
    needs: construccion 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' 
    steps:
    - name: obtener repositorio
      uses: actions/checkout@v2

    - name: desplear con docker compose
      run: docker-compose up -d 

  # job de pruebas
  pruebas:
    needs: construccion 
    runs-on: ubuntu-latest

    steps:
    - name: obtener repositorio
      uses: actions/checkout@v2

    - name: ejecutar pruebas
      run: echo "ejecutando pruebas..." 

  # job de aprobación manual
  #aprobacion-manual:
    #needs: construccion 
    #runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main'
    #steps:
    #- name: aprobación manual
      #uses: chrnorm/deployment-approval-action@v1 
      #with:
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

