name: CI/CD Pipeline

# Definir en qué eventos se ejecutará el workflow
on:
  push:
    # Especificar que solo se ejecute cuando haya cambios en 'nginx/index.html'
    paths:
      - 'nginx/index.html'

jobs:
  build:
    # Especificar el entorno de ejecución
    runs-on: ubuntu-latest

    steps:
    # Primer paso: Chequear el código
    - name: Checkout code
      uses: actions/checkout@v2

    # Segundo paso: Configurar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Tercer paso: Loguearse en DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Cuarto paso: Construir y subir la imagen Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./nginx
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nginx-ci-cd:latest

    # Quinto paso: Desplegar usando docker-compose
    - name: Deploy with docker-compose
      run: |
        docker-compose up -d

